import Foundation

// MARK: - Compression Configuration

struct CompressionConfig: Sendable {
    /// Threshold ratio to trigger compression (0.75 = compress at 75% of context window)
    let compressionTriggerRatio: Double
    /// Ratio of recent messages to always preserve (0.20 = keep last 20%)
    let recentMessagesRatio: Double
    /// Inverse of tokens per character (0.25 = 4 characters per token)
    let tokensPerChar: Double
    
    static let `default` = CompressionConfig(
        compressionTriggerRatio: 0.75,
        recentMessagesRatio: 0.20,
        tokensPerChar: 0.25  // 1 token ≈ 4 characters
    )
}

// MARK: - ConversationCompressor Actor

actor ConversationCompressor: Sendable {
    private let config: CompressionConfig
    
    init(config: CompressionConfig = .default) {
        self.config = config
    }
    
    // MARK: - Token Estimation
    
    /// Estimates token count based on character count using the heuristic: ~4 chars per token
    private func estimateTokens(_ text: String) -> Int {
        Int(Double(text.count) * config.tokensPerChar)
    }
    
    /// Calculates total tokens in a message
    private func messageTokens(_ message: WorkWithFaeConversationMessage) -> Int {
        estimateTokens(message.content)
    }
    
    /// Calculates total tokens across all messages
    private func totalTokens(in messages: [WorkWithFaeConversationMessage]) -> Int {
        messages.reduce(0) { $0 + messageTokens($1) }
    }
    
    // MARK: - Compression Logic
    
    /// Compresses conversation messages if they exceed the configured threshold.
    /// Returns compressed messages with a summary, or original messages if compression not needed.
    func compressIfNeeded(
        messages: [WorkWithFaeConversationMessage],
        contextWindowTokens: Int,
        modelID: String
    ) -> [WorkWithFaeConversationMessage] {
        // Guard against edge cases
        guard messages.count > 10 else { return messages }
        
        // Check if compression is needed
        let totalTokens = totalTokens(in: messages)
        let compressionThreshold = Int(Double(contextWindowTokens) * config.compressionTriggerRatio)
        
        guard totalTokens > compressionThreshold else {
            // Under threshold, no compression needed
            return messages
        }
        
        // Compression is needed
        let recentCount = max(1, Int(Double(messages.count) * config.recentMessagesRatio))
        let recentMessages = Array(messages.suffix(recentCount))
        let messagesToCompress = Array(messages.dropLast(recentCount))
        
        // Create a summary placeholder message (will be replaced with actual LLM response in Task 2)
        let summaryMessage = WorkWithFaeConversationMessage(
            id: UUID(),
            role: "summary",
            content: "[Conversation summary pending - will be generated by LLM in Task 2]",
            timestamp: Date(),
            modelID: modelID,
            providerKind: "fae-localhost"
        )
        
        // Return: oldest compressed messages + summary + recent messages
        return messagesToCompress + [summaryMessage] + recentMessages
    }
    
    // MARK: - Summary Generation (Task 2)
    
    /// Generates a summary of messages using the local LLM.
    /// This method will be fully implemented in Task 2.
    private func generateSummary(
        messages: [WorkWithFaeConversationMessage],
        previousSummary: WorkWithFaeConversationMessage?,
        modelID: String,
        provider: FaeLocalhostCoworkProvider
    ) async throws -> WorkWithFaeConversationMessage {
        // TODO: Implement in Task 2
        // For now, return a placeholder summary
        return WorkWithFaeConversationMessage(
            id: UUID(),
            role: "summary",
            content: "Conversation summary (to be implemented in Task 2)",
            timestamp: Date(),
            modelID: modelID,
            providerKind: "fae-localhost"
        )
    }
}
