import Foundation
import FaeHandoffKit

// MARK: - Chat Types

enum ChatRole: String, Equatable {
    case user
    case assistant
    case tool
    /// Compressed conversation summary generated by the local LLM.
    case summary
}

struct ChatMessage: Identifiable, Equatable {
    let id: UUID
    let role: ChatRole
    let content: String
    let timestamp: Date
    /// Which model generated this message (e.g. "gpt-4o", "claude-opus-4-6"). Nil for user messages.
    let modelID: String?
    /// Which provider generated this message (e.g. "openai", "anthropic", "fae-localhost"). Nil for user messages.
    let providerKind: String?

    init(id: UUID = UUID(), role: ChatRole, content: String, timestamp: Date = Date(), modelID: String? = nil, providerKind: String? = nil) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.modelID = modelID
        self.providerKind = providerKind
    }
}

// MARK: - ConversationController

@MainActor
final class ConversationController: ObservableObject {
    @Published var isListening: Bool = true
    @Published var isConversationPanelOpen: Bool = false
    @Published var isCanvasPanelOpen: Bool = false
    @Published var lastInteractionTimestamp: Date = Date()

    /// Native message store for SwiftUI conversation window.
    @Published var messages: [ChatMessage] = []

    /// Whether the assistant is currently generating a response.
    @Published var isGenerating: Bool = false

    /// Count of deferred/background tool jobs currently running.
    @Published var backgroundToolJobsInFlight: Int = 0

    /// Text currently streaming from the assistant (sentence fragments as they arrive).
    @Published var streamingText: String = ""
    /// Whether a streaming response is actively being built.
    @Published var isStreaming: Bool = false

    /// Friendly label for the loaded LLM, e.g. "Qwen3 8B · Q4_K_M".
    /// Set when the LLM finishes loading; empty until then.
    @Published var loadedModelLabel: String = ""

    /// Live think tokens during an active generation (inside `<think>` blocks).
    @Published var streamingThinkText: String = ""

    /// Completed reasoning trace from the last assistant turn, if thinking was active.
    @Published var completedThinkTrace: String? = nil

    private let maxMessages = 200

    /// Set when a handoff snapshot is restored. The UI observes this to push
    /// the restored entries into the conversation web view.
    @Published private(set) var restoredSnapshot: ConversationSnapshot?

    /// The device name that sent the restored conversation (for banner display).
    @Published private(set) var restoredFromDevice: String?

    func toggleListening() {
        isListening.toggle()
        lastInteractionTimestamp = Date()
        NotificationCenter.default.post(
            name: .faeConversationGateSet,
            object: nil,
            userInfo: ["active": isListening]
        )
    }

    func handleUserSent(_ text: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        lastInteractionTimestamp = Date()
        // Add to conversation panel immediately — typed messages don't go through
        // STT/pendingUserTranscription, so we add them here directly.
        appendMessage(role: .user, content: trimmed)
        NotificationCenter.default.post(
            name: .faeConversationInjectText,
            object: nil,
            userInfo: ["text": trimmed]
        )
    }

    /// Restore conversation state from a handoff snapshot.
    ///
    /// Stores the snapshot so the UI layer can push entries into the web view.
    /// Handles malformed snapshots gracefully — empty entries are accepted but
    /// a nil snapshot is a no-op.
    func restore(from snapshot: ConversationSnapshot, device: String? = nil) {
        restoredSnapshot = snapshot
        restoredFromDevice = device
        lastInteractionTimestamp = Date()
        NSLog("ConversationController: restored %d entries from handoff%@",
              snapshot.entries.count,
              device.map { " (\($0))" } ?? "")
    }

    /// Clear the restored snapshot after the UI has consumed it.
    func clearRestoredSnapshot() {
        restoredSnapshot = nil
        restoredFromDevice = nil
    }

    // MARK: - Message Store

    func appendMessage(role: ChatRole, content: String, modelID: String? = nil, providerKind: String? = nil) {
        let message = ChatMessage(role: role, content: content, modelID: modelID, providerKind: providerKind)
        messages.append(message)
        // FIFO cap at maxMessages
        if messages.count > maxMessages {
            messages.removeFirst(messages.count - maxMessages)
        }
    }

    func clearMessages() {
        messages.removeAll()
    }

    func replaceMessages(_ newMessages: [ChatMessage]) {
        messages = Array(newMessages.suffix(maxMessages))
        streamingText = ""
        isStreaming = false
        isGenerating = false
        streamingThinkText = ""
        completedThinkTrace = nil
    }

    // MARK: - Background Tool Activity

    var isBackgroundLookupActive: Bool {
        backgroundToolJobsInFlight > 0
    }

    func beginBackgroundLookup() {
        backgroundToolJobsInFlight += 1
    }

    func endBackgroundLookup() {
        backgroundToolJobsInFlight = max(0, backgroundToolJobsInFlight - 1)
    }

    func resetBackgroundLookups() {
        backgroundToolJobsInFlight = 0
    }

    // MARK: - Streaming

    func startStreaming() {
        streamingText = ""
        isStreaming = true
    }

    func beginThinkingTurn(placeholderTrace: String? = nil) {
        isGenerating = true
        streamingText = ""
        isStreaming = false
        streamingThinkText = placeholderTrace ?? ""
        completedThinkTrace = nil
    }

    func replaceThinkingTrace(with text: String) {
        streamingThinkText = text
    }

    func appendThinkingTrace(_ text: String) {
        guard !text.isEmpty else { return }
        streamingThinkText += text
    }

    func finalizeThinkingTrace() {
        let trace = streamingThinkText.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trace.isEmpty {
            completedThinkTrace = trace
        }
        streamingThinkText = ""
    }

    func clearThinkingTrace() {
        streamingThinkText = ""
        completedThinkTrace = nil
    }

    func startStreamingReply() {
        finalizeThinkingTrace()
        startStreaming()
    }

    func updateStreaming(text: String) {
        streamingText = text
    }

    func finalizeStreaming(modelID: String? = nil, providerKind: String? = nil) {
        if !streamingText.isEmpty {
            appendMessage(role: .assistant, content: streamingText, modelID: modelID, providerKind: providerKind)
        }
        streamingText = ""
        isStreaming = false
    }

    func cancelStreaming(modelID: String? = nil, providerKind: String? = nil) {
        // Commit any partial text as a message (barge-in or error recovery)
        if !streamingText.isEmpty {
            appendMessage(role: .assistant, content: streamingText, modelID: modelID, providerKind: providerKind)
        }
        streamingText = ""
        isStreaming = false
    }

    // MARK: - Link Detection

    func handleLinkDetected(_ url: String) {
        let trimmed = url.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        // Post as a separate link-detected event, NOT as inject_text.
        // The message text (including the URL) is already injected by handleUserSent.
        // This event is for link-specific handling (preview cards, bookmarks, etc.).
        NotificationCenter.default.post(
            name: .faeConversationLinkDetected,
            object: nil,
            userInfo: ["url": trimmed]
        )
    }
}

extension Notification.Name {
    static let faeConversationInjectText = Notification.Name("faeConversationInjectText")
    static let faeConversationGateSet = Notification.Name("faeConversationGateSet")
    static let faeConversationLinkDetected = Notification.Name("faeConversationLinkDetected")
    /// Posted when the user clicks the collapsed orb to expand it.
    /// The HostCommandBridge forwards this as "conversation.engage" to reset
    /// the direct-address follow-up window so the next utterance is accepted.
    static let faeConversationEngage = Notification.Name("faeConversationEngage")
    /// Posted by WindowStateController when it expands from collapsed to compact.
    /// InputBarView listens for this to restore keyboard focus on the text field.
    static let faeWillFocusInputField = Notification.Name("faeWillFocusInputField")
    /// Posted by Help menu items to pre-fill the input bar with a topic question.
    /// userInfo: ["text": String]
    static let faePrefillInput = Notification.Name("faePrefillInput")
    /// Posted when the push-to-talk key is pressed (hold-to-talk or orb click).
    /// FaeCore listens for this to unmute the microphone.
    static let faePTTPressed = Notification.Name("faePTTPressed")
    /// Posted when the push-to-talk key is released (hold-to-talk mode).
    /// FaeCore listens for this to restore the previous mute state.
    static let faePTTReleased = Notification.Name("faePTTReleased")
    /// Posted when voice.ptt_hotkey_key_code changes so the app re-registers
    /// the hold-to-talk monitor with the new key.
    static let faePTTHotkeyChanged = Notification.Name("faePTTHotkeyChanged")
    /// Posted by the stop button or Cmd+. menu item to cancel the current generation.
    static let faeCancelGeneration = Notification.Name("faeCancelGeneration")
    /// Posted when voice-command routing asks the app to open the Settings window.
    static let faeOpenSettingsRequested = Notification.Name("faeOpenSettingsRequested")
    /// Posted when voice-command routing asks the app to close the Settings window.
    static let faeCloseSettingsRequested = Notification.Name("faeCloseSettingsRequested")
    /// Posted by canvas interactions or voice authority flow to request a governed settings mutation.
    /// userInfo: ["action": String, "value": String, "source": String]
    static let faeGovernanceActionRequested = Notification.Name("faeGovernanceActionRequested")
    /// Posted when the app should open the native speaker-enrollment sheet and capture real audio.
    static let faeStartNativeEnrollmentRequested = Notification.Name("faeStartNativeEnrollmentRequested")
}
